config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :projects
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Nested routes for tasks
  resources :projects, param: :slug do
    resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end

  # Defines the root path route ("/")
  root "home#index"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  has_many :tasks, dependent: :destroy

  validates :title, presence: true
  validates :slug, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :title, presence: true
  validates :project_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @projects = current_user.projects
    else
      @projects = []
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:user_id, :title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task =  @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: project_path(@project) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_path(@project), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: project_path(@project) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url(@project), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find_by!(slug: params[:project_slug])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<section class="flex flex-col items-center mt-5 max-w-xl mx-auto">
  <% if user_signed_in? %>
    <%= link_to "New Project", new_project_path, class: "border rounded-md hover:bg-gray-300 py-4 w-full text-center"  %>
    <!-- Show the user's projects -->
    <section class="mt-5 w-full">
      <% if @projects %>
        <hr class="mb-2"/>
        <h1 class="text-2xl font-semibold text-left">Your projects</h1>
      <% else %>
        <hr class="mb-2"/>
        <h1>No projects yet, 
          <span class="text-cyan-500">
            <%= link_to "create one", new_project_path %>
          </span>
        </h1>
      <% end %>
      <!-- List only 3 projects -->
      <% @projects = @projects[0..2] %>
      <% @projects.each do |project| %>
        <div class="border rounded-md mt-4 p-5">
          <!-- Project title -->
          <p class="text-xl mb-4"><%= project.title %></p>
          <!-- Link to the project -->
          <p><%= link_to "Show this project", project, class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md" %></p>
        </div>
      <% end %>
      <% if @projects.size > 2 %>
        <p class="text-right mt-4">
          <%= link_to "Show all projects", projects_path, class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md" %>
        </p>
      <% end %>
    </section>
  <% else %>
    <h1>Welcome, please 
      <span class="text-cyan-500">
        <%= link_to "sign in", new_user_session_path %>
      </span>
      or 
      <span class="text-cyan-500">
        <%= link_to "sign up", new_user_registration_path %>
      </span>
      to enter.</h1>
  <% end %>
</section>

app/views/layouts/_navbar.html.erb
<header class="flex bg-gray-200 max-w-xl mx-auto h-16 rounded-md mt-4 items-center">
  <% if user_signed_in? %>
    <nav class="flex w-full md:max-w-7xl mx-auto gap-4 p-2 justify-center bg-transparent">
      <ul class="flex flex-row left-0 top-0 h-full items-center">
        <li>
          <%= link_to "Home", root_path, class: "p-2 hover:bg-gray-300 rounded-md mr-4", data: { turbolinks: false } %>
        </li>
        <li class="p-2 hover:bg-gray-300 rounded-md">
          <%= link_to "Log out", destroy_user_session_path, data: { turbolinks: false } %>
        </li>
      </ul>
    </nav>
  <% else %>
    <nav class="flex w-full md:max-w-7xl mx-auto gap-4 p-2 justify-center bg-transparent">
      <ul class="flex flex-row left-0 top-0 h-full items-center">
        <li>
          <%= link_to "Home", root_path, data: { turbolinks: false }, class: "p-2 hover:bg-gray-300 rounded-md mr-4" %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path, class: "p-2 hover:bg-gray-300 rounded-md", data: { turbolinks: false } %>
        </li>
        <li>
          <%= link_to "Log in", new_user_session_path, class: "p-2 hover:bg-gray-300 rounded-md", data: { turbolinks: false } %>
        </li>
      </ul>
    </nav>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StratiaTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-prefetch" content="false">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-gray-100 mx-auto">
    <!-- This file lives in app/views/layouts/_navbar.html.erb -->
    <%= render "layouts/navbar" %>
    <section class="flex flex-col items-center max-w-xl mx-auto">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </section>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%# form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, value: current_user.id, style: "display: none" %>
  </div>
  <div class="md:flex gap-4 items-center">
    <%= form.label :title, style: "display: block", class: "w-full"  %>
    <%= form.text_field :title, class: "rounded-md" %>
  </div>
  <div class="md:flex gap-4 items-center mt-2">
    <%= form.label :description, style: "display: block", class: "w-full"  %>
    <%= form.text_field :description, class: "rounded-md" %>
  </div>
  <div class="mt-4 flex justify-center">
    <%= form.submit "Submit", class:"bg-cyan-500 hover:bg-cyan-600 text-white font-bold py-2 px-4 rounded hover:cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<section class="mt-5">
  <h1 class="text-center text-semibold text-xl">Editing project</h1>
  <section class="flex justify-center items-center">
    <div class="mt-4">
      <%= render "form", project: @project %>
    </div>
  </section>
  <div class="flex text-cyan-700 justify-center mt-4 gap-2">
    <%= link_to "Show this project", @project, class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md"  %>
    <%= link_to "Back to projects", projects_path, class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md"  %>
  </div>
</section>

app/views/projects/index.html.erb
<section class="flex flex-col items-center mt-5 max-w-xl mx-auto">
  <p style="color: green"><%= notice %></p>
  <%= link_to "New Project", new_project_path, class: "border rounded-md hover:bg-gray-300 py-4 w-full text-center"  %>
  <section class="mt-5 w-full">
    <h1 class="text-2xl font-semibold text-left">Your projects</h1>
    <hr class="mb-2"/>
    <% @projects.each do |project| %>
      <div class="border rounded-md mt-4 p-5">
        <!-- Project title -->
        <p class="text-xl mb-4"><%= project.title %></p>
        <!-- Link to the project -->
        <p><%= link_to "Show this project", project, class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md" %></p>
      </div>
    <% end %>
  </section>
</section>

app/views/projects/new.html.erb
<section class="mt-5">
  <h1 class="text-center text-semibold text-xl">New project</h1>
  <section class="flex justify-center items-center">
    <div class="mt-4">
      <%= render "form", project: @project %>
      <br>
      <span class="text-cyan-700">
        <%= link_to "Back to projects", projects_path %>
      </span>
    </div>
  </section>
</section>

app/views/projects/show.html.erb
<section class="flex flex-col mt-5 max-w-xl mx-auto">
  <p style="color: green"><%= notice %></p>
  <h1 class="text-xl font-semibold"> Project information </h1>
  <% if user_signed_in?%>
    <% if current_user.id == @project.user_id %>
      <div class="border rounded-md mt-4 p-5">
        <!-- Project title -->
        <h2 class="text-xl mb-4"><%= @project.title %></h2>
        <hr />
        <!-- Description of the project -->
        <p class="mt-4"><%= @project.description %></p>
      </div>
      <h1 class="text-xl font-semibold mt-5">Tasks</h1>
      <%= link_to "New task", new_project_task_path(@project), class: "border rounded-md hover:bg-gray-300 py-4 w-full text-center"  %>
      <% @project.tasks.each do |task| %>
        <div class="border rounded-md mt-4 p-5">
          <h2 class="text-xl mb-4"><%= task.title %></h2>
          <hr />
          <p class="my-4"><%= task.description%></p>
          <% if task.completed %>
            <span>Task completed</span>
          <% else %>
            <span>Task has not been completed</span>
          <% end %>
          <%= link_to "Edit this task", edit_project_task_path(@project, task), class:"block text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md" %>
        </div>
      <% end %>
      <div class="flex justify-center mt-4 items-center">
        <%= link_to "Edit this project", edit_project_path(@project), class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md" %>
        <%= link_to "Back to projects", projects_path, class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md" %>
      </div>
      <div class="flex justify-center mt-5 items-center">
        <%= button_to "Destroy this project", @project, method: :delete %>
      </div>
    <% else %>
      <p class="text-center"> You don't have access to this project </p>
    <% end %>
  <% end %>
</section>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @task]) do |form| %>
  <%= form.hidden_field :project_slug, value: @project.slug %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="md:flex gap-4 items-center">
    <%= form.label :title, style: "display: block", class: "w-full"  %>
    <%= form.text_field :title, class: "rounded-md" %>
  </div>
  <div class="md:flex gap-4 items-center mt-2">
    <%= form.label :description, style: "display: block", class: "w-full"  %>
    <%= form.text_field :description, class: "rounded-md" %>
  </div>
  <div class="flex gap-4 items-center mt-2">
    <%= form.label :completed, style: "display: block" %>
    <div class="flex items-center">
      <%= form.check_box :completed, class: "rounded-sm" %>
    </div>
  </div>
  <div class="mt-4 flex justify-center">
    <%= form.submit "Submit", class:"bg-cyan-500 hover:bg-cyan-600 text-white font-bold py-2 px-4 rounded hover:cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= task.completed %>
  </p>

</div>

app/views/tasks/edit.html.erb
<section class="mt-5">
  <h1 class="text-center text-semibold text-xl">Editing task</h1>
  <section class="flex justify-center items-center">
    <div class="mt-4">
      <%= render "form", task: @task %>
      <br>
      <div class="flex text-cyan-700 justify-center mt-4 gap-2">
        <%= link_to "Back to project", project_path(@project), class:"text-cyan-500 hover:text-cyan-600 hover:bg-gray-200 p-2 rounded-md" %>
      </div>
    </div>
  </section>
</section>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Tasks</h1>
<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", project_task_path(@project, task) %>
    </p>
    <p>
      <%= link_to "Back to project", project_path(@project) %>
    </p>
  <% end %>
</div>
<%= link_to "New task", new_project_task_path(@project) %>

app/views/tasks/new.html.erb
<section class="mt-5">
  <h1 class="text-center text-semibold text-xl">New task</h1>
  <section class="flex justify-center items-center">
    <div class="mt-4">
      <%= render "form", task: @task %>
      <br>
      <div class="flex text-cyan-700 justify-center mt-4 gap-2">
        <%= link_to "Back to project", project_path(@project) %>
      </div>
    </div>
  </section>
</section>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @task %>
<div>
  <%= link_to "Edit this task", edit_project_task_path(@project, @task) %> |
  <%= link_to "Back to tasks", project_tasks_path(@project) %>
  <%= link_to "Back to project", project_path(@project) %>
  <%= button_to "Destroy this task", @task, method: :delete %>
</div>